// Static NSE ticker → sector map. Covers the most-traded stocks; unmapped
// tickers fall back to "Other". Update sparingly — sectoral classification
// rarely changes for established companies.

const SECTOR_MAP: Record<string, string> = {
  // ── Banking & Financial Services ──
  "HDFCBANK": "Banking",
  "ICICIBANK": "Banking",
  "SBIN": "Banking",
  "AXISBANK": "Banking",
  "KOTAKBANK": "Banking",
  "INDUSINDBK": "Banking",
  "BANKBARODA": "Banking",
  "PNB": "Banking",
  "FEDERALBNK": "Banking",
  "IDFCFIRSTB": "Banking",
  "CANBK": "Banking",
  "BANDHANBNK": "Banking",
  "AUBANK": "Banking",
  "BAJFINANCE": "Financial Services",
  "BAJAJFINSV": "Financial Services",
  "HDFCLIFE": "Financial Services",
  "SBILIFE": "Financial Services",
  "ICICIPRULI": "Financial Services",
  "ICICIGI": "Financial Services",
  "LICI": "Financial Services",
  "CHOLAFIN": "Financial Services",
  "SHRIRAMFIN": "Financial Services",
  "MUTHOOTFIN": "Financial Services",
  "MFSL": "Financial Services",
  "RECLTD": "Financial Services",
  "PFC": "Financial Services",
  "IRFC": "Financial Services",
  "HUDCO": "Financial Services",
  "LICHSGFIN": "Financial Services",
  "PEL": "Financial Services",

  // ── IT & Tech ──
  "TCS": "IT",
  "INFY": "IT",
  "WIPRO": "IT",
  "HCLTECH": "IT",
  "TECHM": "IT",
  "LTIM": "IT",
  "MPHASIS": "IT",
  "PERSISTENT": "IT",
  "COFORGE": "IT",
  "OFSS": "IT",
  "LTTS": "IT",
  "KPITTECH": "IT",
  "TATAELXSI": "IT",
  "ZENSARTECH": "IT",
  "BIRLASOFT": "IT",

  // ── Auto ──
  "MARUTI": "Auto",
  "TATAMOTORS": "Auto",
  "M&M": "Auto",
  "BAJAJ-AUTO": "Auto",
  "BAJAJAUTO": "Auto",
  "EICHERMOT": "Auto",
  "HEROMOTOCO": "Auto",
  "TVSMOTOR": "Auto",
  "ASHOKLEY": "Auto",
  "MOTHERSON": "Auto",
  "BOSCHLTD": "Auto",
  "BHARATFORG": "Auto",
  "BALKRISIND": "Auto",
  "EXIDEIND": "Auto",
  "MRF": "Auto",
  "APOLLOTYRE": "Auto",
  "CEATLTD": "Auto",
  "ESCORTS": "Auto",

  // ── Pharma & Healthcare ──
  "SUNPHARMA": "Pharma",
  "DRREDDY": "Pharma",
  "CIPLA": "Pharma",
  "DIVISLAB": "Pharma",
  "LUPIN": "Pharma",
  "AUROPHARMA": "Pharma",
  "TORNTPHARM": "Pharma",
  "BIOCON": "Pharma",
  "ALKEM": "Pharma",
  "ZYDUSLIFE": "Pharma",
  "GLAND": "Pharma",
  "GLENMARK": "Pharma",
  "IPCALAB": "Pharma",
  "LAURUSLABS": "Pharma",
  "APOLLOHOSP": "Healthcare",
  "MAXHEALTH": "Healthcare",
  "FORTIS": "Healthcare",
  "METROPOLIS": "Healthcare",
  "LALPATHLAB": "Healthcare",

  // ── FMCG ──
  "HINDUNILVR": "FMCG",
  "ITC": "FMCG",
  "NESTLEIND": "FMCG",
  "BRITANNIA": "FMCG",
  "DABUR": "FMCG",
  "GODREJCP": "FMCG",
  "MARICO": "FMCG",
  "COLPAL": "FMCG",
  "TATACONSUM": "FMCG",
  "VBL": "FMCG",
  "UBL": "FMCG",
  "RADICO": "FMCG",
  "EMAMILTD": "FMCG",

  // ── Energy / Oil & Gas ──
  "RELIANCE": "Energy",
  "ONGC": "Energy",
  "NTPC": "Energy",
  "POWERGRID": "Energy",
  "COALINDIA": "Energy",
  "BPCL": "Energy",
  "IOC": "Energy",
  "HINDPETRO": "Energy",
  "GAIL": "Energy",
  "ADANIPOWER": "Energy",
  "ADANIGREEN": "Energy",
  "ADANIENSOL": "Energy",
  "TATAPOWER": "Energy",
  "JSWENERGY": "Energy",
  "NHPC": "Energy",
  "SJVN": "Energy",
  "PETRONET": "Energy",
  "OIL": "Energy",
  "MGL": "Energy",
  "IGL": "Energy",
  "GUJGASLTD": "Energy",

  // ── Metals & Mining ──
  "TATASTEEL": "Metals",
  "JSWSTEEL": "Metals",
  "HINDALCO": "Metals",
  "VEDL": "Metals",
  "SAIL": "Metals",
  "JINDALSTEL": "Metals",
  "NMDC": "Metals",
  "NATIONALUM": "Metals",
  "HINDZINC": "Metals",
  "APLAPOLLO": "Metals",
  "JSL": "Metals",
  "RATNAMANI": "Metals",

  // ── Cement ──
  "ULTRACEMCO": "Cement",
  "SHREECEM": "Cement",
  "AMBUJACEM": "Cement",
  "ACC": "Cement",
  "DALBHARAT": "Cement",
  "RAMCOCEM": "Cement",
  "JKCEMENT": "Cement",
  "INDIACEM": "Cement",

  // ── Telecom & Media ──
  "BHARTIARTL": "Telecom",
  "IDEA": "Telecom",
  "INDUSTOWER": "Telecom",
  "TATACOMM": "Telecom",
  "RCOM": "Telecom",
  "ZEEL": "Media",
  "SUNTV": "Media",
  "PVRINOX": "Media",
  "NETWORK18": "Media",

  // ── Consumer Discretionary / Retail ──
  "TITAN": "Consumer",
  "TRENT": "Consumer",
  "DMART": "Retail",
  "ABFRL": "Consumer",
  "PAGEIND": "Consumer",
  "BATAINDIA": "Consumer",
  "HAVELLS": "Consumer",
  "DIXON": "Consumer",
  "RELAXO": "Consumer",
  "VOLTAS": "Consumer",
  "WHIRLPOOL": "Consumer",
  "CROMPTON": "Consumer",
  "BLUESTARCO": "Consumer",
  "JUBLFOOD": "Consumer",
  "DEVYANI": "Consumer",
  "NYKAA": "Consumer",
  "FSNL": "Consumer",
  "ZOMATO": "Consumer",
  "ETERNAL": "Consumer",

  // ── Capital Goods / Engineering ──
  "LT": "Capital Goods",
  "SIEMENS": "Capital Goods",
  "ABB": "Capital Goods",
  "BEL": "Capital Goods",
  "BHEL": "Capital Goods",
  "CUMMINSIND": "Capital Goods",
  "THERMAX": "Capital Goods",
  "AIAENG": "Capital Goods",
  "POLYCAB": "Capital Goods",
  "KEI": "Capital Goods",
  "HAL": "Defence",
  "BDL": "Defence",
  "MAZDOCK": "Defence",
  "GRSE": "Defence",
  "COCHINSHIP": "Defence",

  // ── Cement / Construction / Real Estate ──
  "DLF": "Real Estate",
  "GODREJPROP": "Real Estate",
  "OBEROIRLTY": "Real Estate",
  "PRESTIGE": "Real Estate",
  "BRIGADE": "Real Estate",
  "PHOENIXLTD": "Real Estate",
  "LODHA": "Real Estate",

  // ── Chemicals ──
  "PIDILITIND": "Chemicals",
  "UPL": "Chemicals",
  "AARTIIND": "Chemicals",
  "DEEPAKNTR": "Chemicals",
  "PIIND": "Chemicals",
  "SRF": "Chemicals",
  "ATUL": "Chemicals",
  "NAVINFLUOR": "Chemicals",
  "TATACHEM": "Chemicals",
  "COROMANDEL": "Chemicals",
  "BASF": "Chemicals",
  "GNFC": "Chemicals",
  "FACT": "Chemicals",

  // ── Logistics / Transport ──
  "ADANIPORTS": "Logistics",
  "CONCOR": "Logistics",
  "BLUEDART": "Logistics",
  "TCI": "Logistics",
  "DELHIVERY": "Logistics",
  "GATI": "Logistics",
  "INDIGO": "Aviation",
  "SPICEJET": "Aviation",
  "INTERGLOBE": "Aviation",

  // ── Diversified / Conglomerates ──
  "ADANIENT": "Diversified",
  "GRASIM": "Diversified",
  "ITCHOTELS": "Hotels",
  "INDHOTEL": "Hotels",
  "EIHOTEL": "Hotels",
  "CHALET": "Hotels",
  "LEMONTREE": "Hotels",

  // ── Crypto (yfinance suffix-less) ──
  "BTC-USD": "Crypto",
  "ETH-USD": "Crypto",
  "SOL-USD": "Crypto",
  "BNB-USD": "Crypto",
  "ADA-USD": "Crypto",
  "XRP-USD": "Crypto",
  "DOGE-USD": "Crypto",
  "MATIC-USD": "Crypto",
  "AVAX-USD": "Crypto",
  "LINK-USD": "Crypto",
  "DOT-USD": "Crypto",
  "TRX-USD": "Crypto",
  "ATOM-USD": "Crypto",
  "LTC-USD": "Crypto",
  "BCH-USD": "Crypto",
  "UNI-USD": "Crypto",
  "NEAR-USD": "Crypto",
};

// Display order — most actively traded sectors first
export const SECTOR_ORDER = [
  "Banking",
  "IT",
  "Auto",
  "Pharma",
  "Healthcare",
  "FMCG",
  "Energy",
  "Metals",
  "Financial Services",
  "Capital Goods",
  "Defence",
  "Cement",
  "Chemicals",
  "Telecom",
  "Consumer",
  "Retail",
  "Real Estate",
  "Logistics",
  "Aviation",
  "Hotels",
  "Media",
  "Diversified",
  "Crypto",
  "Other",
];

export function sectorOf(ticker: string): string {
  if (!ticker) return "Other";
  // Strip common suffixes
  const clean = ticker.replace(/\.(NS|BO)$/i, "").toUpperCase();
  return SECTOR_MAP[clean] || "Other";
}
